name: MLflow Project CI

on: [push]

permissions:
  contents: write

jobs:
  run-ml-project:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: |
          python --version
          pip --version
          env

      - name: Install dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: '3.12.7'
          activate-environment: credit_risk_env
          environment-file: MLProject/conda.yaml

      - name: Run mlflow project
        shell: bash -l {0}
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/Eksperimen_SML_Muhammad-Restu-Ilahi.mlflow
        run: |
          mlflow run MLProject --experiment-name "CI_Workflow_Muhammad-Restu-Ilahi" --run-name "CI_Workflow_Muhammad-Restu-Ilahi_Run_v${{ github.run_number }}"

      - name: Get latest MLflow run_id
        shell: bash -l {0}
        id: get_run_id
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/Eksperimen_SML_Muhammad-Restu-Ilahi.mlflow
        run: |
          # Mengambil Run ID terbaru dari eksperimen terkait
          RUN_ID=$(python -c "import mlflow; exp = mlflow.get_experiment_by_name('CI_Workflow_Muhammad-Restu-Ilahi'); runs = mlflow.search_runs(experiment_ids=[exp.experiment_id], max_results=1, order_by=['attributes.start_time DESC']); print(runs['run_id'][0])")
          
          echo "LATEST_RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest Run ID found: $RUN_ID"

      - name: Install Python dependencies
        shell: bash -l {0}
        run: |
          pip install --upgrade pip
          mlserver --version || pip install mlserver mlserver-mlflow
          python -c "import mlflow; import sklearn; print('✅ Environment and Infrastructure Ready')"
          echo "Infrastructure tools verified!"

      - name: Upload to GitHub
        shell: bash -l {0}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Arahkan ke folder artifacts
          git add artifacts/
          
          git commit -m "chore: update production artifacts from run ${{ github.run_number }} [skip ci]" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Model
        shell: bash -l {0}
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/Eksperimen_SML_Muhammad-Restu-Ilahi.mlflow
        run: |
          mlflow models build-docker -m "models:/model_credit_risk/latest" -n credit-risk-app" --enable-mlserver --env-manager local

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag credit-risk-app ${{ secrets.DOCKERHUB_USERNAME }}/credit-risk-app:latest
          docker tag credit-risk-app ${{ secrets.DOCKERHUB_USERNAME }}/credit-risk-app:${{ env.LATEST_RUN_ID }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/credit-risk-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/credit-risk-app:${{ env.LATEST_RUN_ID }}