name: MLflow Project CI

on: [push]

permissions:
  contents: write

jobs:
  run-ml-project:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: |
          python --version
          pip --version
          env

      - name: Install dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: '3.12.7'
          activate-environment: credit_risk_env
          environment-file: MLProject/conda.yaml

      - name: Run mlflow project
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/mrestuilahi1405/Eksperimen_SML_Muhammad-Restu-Ilahi.mlflow
        run: |
          mlflow run MLProject --experiment-name "CI_Workflow_Muhammad-Restu-Ilahi" --run-name "CI_Workflow_Muhammad-Restu-Ilahi_Run_v${{ github.run_number }}"

      - name: Get latest MLflow run_id
        id: get_run_id
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/mrestuilahi1405/Eksperimen_SML_Muhammad-Restu-Ilahi.mlflow
        run: |
          # Mengambil Run ID terbaru dari eksperimen terkait
          RUN_ID=$(mlflow runs search --experiment-names "CI_Workflow_Muhammad-Restu-Ilahi" --max-results 1 --output csv | tail -n 1 | cut -d, -f1)
          echo "LATEST_RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest Run ID found: $RUN_ID"

      - name: Install Python dependencies
        run: pip install mlserver mlserver-mlflow

      - uses: actions/upload-artifact@v4
        with:
          name: model-artifacts-run-${{ github.run_number }}
          path: MLProject/artifacts/
          retention-days: 7

      - name: Upload to GitHub
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Arahkan ke folder artifacts di dalam subfolder MLProject sesuai struktur fotomu
          git add MLProject/artifacts/
          
          git commit -m "chore: update production artifacts from run ${{ github.run_number }} [skip ci]" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Model
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: https://dagshub.com/mrestuilahi1405/Eksperimen_SML_Muhammad-Restu-Ilahi.mlflow
        run: |
          mlflow models build-docker -m "models:/model_credit_risk/latest" -n "mrestuilahi1405/credit-risk-app:latest" --enable-mlserver

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag credit-risk-app ${{ secrets.DOCKERHUB_USERNAME }}/credit-risk-app:latest
          docker tag credit-risk-app ${{ secrets.DOCKERHUB_USERNAME }}/credit-risk-app:${{ env.LATEST_RUN_ID }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/credit-risk-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/credit-risk-app:${{ env.LATEST_RUN_ID }}